GET http://localhost:8080/events?service=emailer&limit=5
Accept: application/json

###
POST http://localhost:8080/events
Content-Type: application/json
Idempotency-Key: 1

{
  "name": "User.Created",
  "entityId": "1"
}
